<a href="https://colab.research.google.com/github/joncalle/ML2/blob/main/Chrun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [10]:
chr = pd.read_csv("https://raw.githubusercontent.com/joncalle/ML2/main/ChurnData.csv")
print(chr.shape) # print rows, columns
chr.head(10).T     # dump first 2 rows

(5630, 20)


0       1           2  \
CustomerID                                50001   50002       50003   
Churn                                         1       1           1   
Tenure                                      4.0     NaN         NaN   
PreferredLoginDevice               Mobile Phone   Phone       Phone   
CityTier                                      3       1           1   
WarehouseToHome                             6.0     8.0        30.0   
PreferredPaymentMode                 Debit Card     UPI  Debit Card   
Gender                                   Female    Male        Male   
HourSpendOnApp                              3.0     3.0         2.0   
NumberOfDeviceRegistered                      3       4           4   
PreferedOrderCat             Laptop & Accessory  Mobile      Mobile   
SatisfactionScore                             2       3           3   
MaritalStatus                            Single  Single      Single   
NumberOfAddress                               9       7           6   
Complain                                      1       1           1   
OrderAmountHikeFromlastYear                11.0    15.0        14.0   
CouponUsed                                  1.0     0.0         0.0   
OrderCount                                  1.0     1.0         1.0   
DaySinceLastOrder                           5.0     0.0         3.0   
CashbackAmount                              160     121         120   

                                              3       4             5  \
CustomerID                                50004   50005         50006   
Churn                                         1       1             1   
Tenure                                      0.0     0.0           0.0   
PreferredLoginDevice                      Phone   Phone      Computer   
CityTier                                      3       1             1   
WarehouseToHome                            15.0    12.0          22.0   
PreferredPaymentMode                 Debit Card      CC    Debit Card   
Gender                                     Male    Male        Female   
HourSpendOnApp                              2.0     NaN           3.0   
NumberOfDeviceRegistered                      4       3             5   
PreferedOrderCat             Laptop & Accessory  Mobile  Mobile Phone   
SatisfactionScore                             5       5             5   
MaritalStatus                            Single  Single        Single   
NumberOfAddress                               8       3             2   
Complain                                      0       0             1   
OrderAmountHikeFromlastYear                23.0    11.0          22.0   
CouponUsed                                  0.0     1.0           4.0   
OrderCount                                  1.0     1.0           6.0   
DaySinceLastOrder                           3.0     3.0           7.0   
CashbackAmount                              134     130           139   

                                              6         7         8  \
CustomerID                                50007     50008     50009   
Churn                                         1         1         1   
Tenure                                      NaN       NaN      13.0   
PreferredLoginDevice                      Phone     Phone     Phone   
CityTier                                      3         1         3   
WarehouseToHome                            11.0       6.0       9.0   
PreferredPaymentMode           Cash on Delivery        CC  E wallet   
Gender                                     Male      Male      Male   
HourSpendOnApp                              2.0       3.0       NaN   
NumberOfDeviceRegistered                      3         3         4   
PreferedOrderCat             Laptop & Accessory    Mobile    Mobile   
SatisfactionScore                             2         2         3   
MaritalStatus                          Divorced  Divorced  Divorced   
NumberOfAddress           

In [7]:
#verify there are no missing values
chr.isna().sum()

CustomerID                       0
Churn                            0
Tenure                         264
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                251
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 255
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    265
CouponUsed                     256
OrderCount                     258
DaySinceLastOrder              307
CashbackAmount                   0
dtype: int64

In [12]:
chr = chr.fillna(0)
chr.isnull().sum()

CustomerID                     0
Churn                          0
Tenure                         0
PreferredLoginDevice           0
CityTier                       0
WarehouseToHome                0
PreferredPaymentMode           0
Gender                         0
HourSpendOnApp                 0
NumberOfDeviceRegistered       0
PreferedOrderCat               0
SatisfactionScore              0
MaritalStatus                  0
NumberOfAddress                0
Complain                       0
OrderAmountHikeFromlastYear    0
CouponUsed                     0
OrderCount                     0
DaySinceLastOrder              0
CashbackAmount                 0
dtype: int64

In [13]:
for col in chr:
  print(chr[col].unique())

[50001 50002 50003 ... 55628 55629 55630]
[1 0]
[ 4.  0. 13. 11.  9. 19. 20. 14.  8. 18.  5.  2. 30.  1. 23.  3. 29.  6.
 26. 28.  7. 24. 25. 10. 15. 22. 27. 16. 12. 21. 17. 50. 60. 31. 51. 61.]
['Mobile Phone' 'Phone' 'Computer']
[3 1 2]
[  6.   8.  30.  15.  12.  22.  11.   9.  31.  18.  13.  20.  29.  28.
  26.  14.   0.  10.  27.  17.  23.  33.  19.  35.  24.  16.  25.  32.
  34.   5.  21. 126.   7.  36. 127.]
['Debit Card' 'UPI' 'CC' 'Cash on Delivery' 'E wallet' 'COD' 'Credit Card']
['Female' 'Male']
[3. 2. 0. 1. 4. 5.]
[3 4 5 2 1 6]
['Laptop & Accessory' 'Mobile' 'Mobile Phone' 'Others' 'Fashion' 'Grocery']
[2 3 5 4 1]
['Single' 'Divorced' 'Married']
[ 9  7  6  8  3  2  4 10  1  5 19 21 11 20 22]
[1 0]
[11. 15. 14. 23. 22. 16. 12.  0. 13. 17. 18. 24. 19. 20. 21. 25. 26.]
[ 1.  0.  4.  2.  9.  6. 11.  7. 12. 10.  5.  3. 13. 15.  8. 14. 16.]
[ 1.  6.  2. 15.  4.  7.  3.  9.  0. 11.  5. 12. 10.  8. 13. 14. 16.]
[ 5.  0.  3.  7.  2.  1.  8.  6.  4. 15.  9. 11. 10. 13. 12. 17. 16. 14